# Generated by Django 4.2.1 on 2023-06-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='is_within',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_within', to=settings.AUTH_USER_MODEL),
        ),
    ]
